# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pytdproxy/streamer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18pytdproxy/streamer.proto\x12\x0etdproxy_protos\x1a\x1cgoogle/protobuf/struct.proto\"\x0e\n\x0c\x45mptyMessage\"\x1c\n\x0cSubscription\x12\x0c\n\x04name\x18\x01 \x01(\t\"4\n\x10SubscribeRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\ntopic_name\x18\x02 \x01(\t\"j\n\x0bSendRequest\x12\x10\n\x08sub_name\x18\x01 \x01(\t\x12\x0f\n\x07service\x18\x02 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x03 \x01(\t\x12\'\n\x06params\x18\x04 \x01(\x0b\x32\x17.google.protobuf.Struct\"\x1e\n\x0cSendResponse\x12\x0e\n\x06status\x18\x01 \x01(\x03\"0\n\x07Message\x12%\n\x04info\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct2\xe9\x01\n\x0fStreamerService\x12H\n\tSubscribe\x12 .tdproxy_protos.SubscribeRequest\x1a\x17.tdproxy_protos.Message0\x01\x12I\n\x0bUnsubscribe\x12\x1c.tdproxy_protos.Subscription\x1a\x1c.tdproxy_protos.EmptyMessage\x12\x41\n\x04Send\x12\x1b.tdproxy_protos.SendRequest\x1a\x1c.tdproxy_protos.SendResponseB\x10Z\x0etdproxy/protosb\x06proto3')



_EMPTYMESSAGE = DESCRIPTOR.message_types_by_name['EmptyMessage']
_SUBSCRIPTION = DESCRIPTOR.message_types_by_name['Subscription']
_SUBSCRIBEREQUEST = DESCRIPTOR.message_types_by_name['SubscribeRequest']
_SENDREQUEST = DESCRIPTOR.message_types_by_name['SendRequest']
_SENDRESPONSE = DESCRIPTOR.message_types_by_name['SendResponse']
_MESSAGE = DESCRIPTOR.message_types_by_name['Message']
EmptyMessage = _reflection.GeneratedProtocolMessageType('EmptyMessage', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYMESSAGE,
  '__module__' : 'pytdproxy.streamer_pb2'
  # @@protoc_insertion_point(class_scope:tdproxy_protos.EmptyMessage)
  })
_sym_db.RegisterMessage(EmptyMessage)

Subscription = _reflection.GeneratedProtocolMessageType('Subscription', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIPTION,
  '__module__' : 'pytdproxy.streamer_pb2'
  # @@protoc_insertion_point(class_scope:tdproxy_protos.Subscription)
  })
_sym_db.RegisterMessage(Subscription)

SubscribeRequest = _reflection.GeneratedProtocolMessageType('SubscribeRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBEREQUEST,
  '__module__' : 'pytdproxy.streamer_pb2'
  # @@protoc_insertion_point(class_scope:tdproxy_protos.SubscribeRequest)
  })
_sym_db.RegisterMessage(SubscribeRequest)

SendRequest = _reflection.GeneratedProtocolMessageType('SendRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENDREQUEST,
  '__module__' : 'pytdproxy.streamer_pb2'
  # @@protoc_insertion_point(class_scope:tdproxy_protos.SendRequest)
  })
_sym_db.RegisterMessage(SendRequest)

SendResponse = _reflection.GeneratedProtocolMessageType('SendResponse', (_message.Message,), {
  'DESCRIPTOR' : _SENDRESPONSE,
  '__module__' : 'pytdproxy.streamer_pb2'
  # @@protoc_insertion_point(class_scope:tdproxy_protos.SendResponse)
  })
_sym_db.RegisterMessage(SendResponse)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'pytdproxy.streamer_pb2'
  # @@protoc_insertion_point(class_scope:tdproxy_protos.Message)
  })
_sym_db.RegisterMessage(Message)

_STREAMERSERVICE = DESCRIPTOR.services_by_name['StreamerService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\016tdproxy/protos'
  _EMPTYMESSAGE._serialized_start=74
  _EMPTYMESSAGE._serialized_end=88
  _SUBSCRIPTION._serialized_start=90
  _SUBSCRIPTION._serialized_end=118
  _SUBSCRIBEREQUEST._serialized_start=120
  _SUBSCRIBEREQUEST._serialized_end=172
  _SENDREQUEST._serialized_start=174
  _SENDREQUEST._serialized_end=280
  _SENDRESPONSE._serialized_start=282
  _SENDRESPONSE._serialized_end=312
  _MESSAGE._serialized_start=314
  _MESSAGE._serialized_end=362
  _STREAMERSERVICE._serialized_start=365
  _STREAMERSERVICE._serialized_end=598
# @@protoc_insertion_point(module_scope)
