# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pytdproxy/tickers.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17pytdproxy/tickers.proto\x12\x06protos\x1a\x1cgoogle/protobuf/struct.proto\"Z\n\x06Ticker\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x19\n\x11last_refreshed_at\x18\x02 \x01(\t\x12%\n\x04info\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct\"P\n\x11GetTickersRequest\x12\x0f\n\x07symbols\x18\x01 \x03(\t\x12\x19\n\x0crefresh_type\x18\x02 \x01(\x05H\x00\x88\x01\x01\x42\x0f\n\r_refresh_type\"\x85\x02\n\x12GetTickersResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x38\n\x07tickers\x18\x02 \x03(\x0b\x32\'.protos.GetTickersResponse.TickersEntry\x12\x36\n\x06\x65rrors\x18\x03 \x03(\x0b\x32&.protos.GetTickersResponse.ErrorsEntry\x1a>\n\x0cTickersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1d\n\x05value\x18\x02 \x01(\x0b\x32\x0e.protos.Ticker:\x02\x38\x01\x1a-\n\x0b\x45rrorsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32V\n\rTickerService\x12\x45\n\nGetTickers\x12\x19.protos.GetTickersRequest\x1a\x1a.protos.GetTickersResponse\"\x00\x42\x1aZ\x18legfinder/tdproxy/protosb\x06proto3')



_TICKER = DESCRIPTOR.message_types_by_name['Ticker']
_GETTICKERSREQUEST = DESCRIPTOR.message_types_by_name['GetTickersRequest']
_GETTICKERSRESPONSE = DESCRIPTOR.message_types_by_name['GetTickersResponse']
_GETTICKERSRESPONSE_TICKERSENTRY = _GETTICKERSRESPONSE.nested_types_by_name['TickersEntry']
_GETTICKERSRESPONSE_ERRORSENTRY = _GETTICKERSRESPONSE.nested_types_by_name['ErrorsEntry']
Ticker = _reflection.GeneratedProtocolMessageType('Ticker', (_message.Message,), {
  'DESCRIPTOR' : _TICKER,
  '__module__' : 'pytdproxy.tickers_pb2'
  # @@protoc_insertion_point(class_scope:protos.Ticker)
  })
_sym_db.RegisterMessage(Ticker)

GetTickersRequest = _reflection.GeneratedProtocolMessageType('GetTickersRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETTICKERSREQUEST,
  '__module__' : 'pytdproxy.tickers_pb2'
  # @@protoc_insertion_point(class_scope:protos.GetTickersRequest)
  })
_sym_db.RegisterMessage(GetTickersRequest)

GetTickersResponse = _reflection.GeneratedProtocolMessageType('GetTickersResponse', (_message.Message,), {

  'TickersEntry' : _reflection.GeneratedProtocolMessageType('TickersEntry', (_message.Message,), {
    'DESCRIPTOR' : _GETTICKERSRESPONSE_TICKERSENTRY,
    '__module__' : 'pytdproxy.tickers_pb2'
    # @@protoc_insertion_point(class_scope:protos.GetTickersResponse.TickersEntry)
    })
  ,

  'ErrorsEntry' : _reflection.GeneratedProtocolMessageType('ErrorsEntry', (_message.Message,), {
    'DESCRIPTOR' : _GETTICKERSRESPONSE_ERRORSENTRY,
    '__module__' : 'pytdproxy.tickers_pb2'
    # @@protoc_insertion_point(class_scope:protos.GetTickersResponse.ErrorsEntry)
    })
  ,
  'DESCRIPTOR' : _GETTICKERSRESPONSE,
  '__module__' : 'pytdproxy.tickers_pb2'
  # @@protoc_insertion_point(class_scope:protos.GetTickersResponse)
  })
_sym_db.RegisterMessage(GetTickersResponse)
_sym_db.RegisterMessage(GetTickersResponse.TickersEntry)
_sym_db.RegisterMessage(GetTickersResponse.ErrorsEntry)

_TICKERSERVICE = DESCRIPTOR.services_by_name['TickerService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\030legfinder/tdproxy/protos'
  _GETTICKERSRESPONSE_TICKERSENTRY._options = None
  _GETTICKERSRESPONSE_TICKERSENTRY._serialized_options = b'8\001'
  _GETTICKERSRESPONSE_ERRORSENTRY._options = None
  _GETTICKERSRESPONSE_ERRORSENTRY._serialized_options = b'8\001'
  _TICKER._serialized_start=65
  _TICKER._serialized_end=155
  _GETTICKERSREQUEST._serialized_start=157
  _GETTICKERSREQUEST._serialized_end=237
  _GETTICKERSRESPONSE._serialized_start=240
  _GETTICKERSRESPONSE._serialized_end=501
  _GETTICKERSRESPONSE_TICKERSENTRY._serialized_start=392
  _GETTICKERSRESPONSE_TICKERSENTRY._serialized_end=454
  _GETTICKERSRESPONSE_ERRORSENTRY._serialized_start=456
  _GETTICKERSRESPONSE_ERRORSENTRY._serialized_end=501
  _TICKERSERVICE._serialized_start=503
  _TICKERSERVICE._serialized_end=589
# @@protoc_insertion_point(module_scope)
